# Generated by Django 4.2.27 on 2025-12-12 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DetectionTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='任务ID')),
                ('file_name', models.CharField(max_length=256, verbose_name='文件名')),
                ('status', models.CharField(choices=[('pending', '等待中'), ('running', '运行中'), ('completed', '已完成'), ('failed', '失败')], default='pending', max_length=20, verbose_name='状态')),
                ('total_count', models.IntegerField(default=0, verbose_name='总记录数')),
                ('processed_count', models.IntegerField(default=0, verbose_name='已处理数')),
                ('anomaly_count', models.IntegerField(default=0, verbose_name='异常数')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='错误信息')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '检测任务',
                'verbose_name_plural': '检测任务',
                'db_table': 'detection_tasks',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DetectionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(db_index=True, max_length=64, verbose_name='设备ID')),
                ('timestamp', models.DateTimeField(db_index=True, verbose_name='检测时间')),
                ('src_ip', models.GenericIPAddressField(verbose_name='源IP')),
                ('dst_ip', models.GenericIPAddressField(verbose_name='目的IP')),
                ('src_port', models.IntegerField(blank=True, null=True, verbose_name='源端口')),
                ('dst_port', models.IntegerField(blank=True, null=True, verbose_name='目的端口')),
                ('protocol', models.CharField(default='TCP', max_length=10, verbose_name='协议')),
                ('duration', models.FloatField(default=0, verbose_name='持续时间')),
                ('orig_bytes', models.BigIntegerField(default=0, verbose_name='发送字节数')),
                ('resp_bytes', models.BigIntegerField(default=0, verbose_name='接收字节数')),
                ('orig_pkts', models.IntegerField(default=0, verbose_name='发送包数')),
                ('resp_pkts', models.IntegerField(default=0, verbose_name='接收包数')),
                ('is_anomaly', models.BooleanField(db_index=True, default=False, verbose_name='是否异常')),
                ('attack_type', models.CharField(choices=[('normal', '正常'), ('ddos', 'DDoS攻击'), ('port_scan', '端口扫描'), ('unauthorized', '越权访问'), ('malformed', '异常指令'), ('unknown', '未知威胁')], default='normal', max_length=20, verbose_name='攻击类型')),
                ('confidence', models.FloatField(default=0.0, verbose_name='置信度')),
                ('anomaly_score', models.FloatField(default=0.0, verbose_name='异常分数')),
                ('model_version', models.CharField(default='v1.0', max_length=32, verbose_name='模型版本')),
                ('inference_time', models.FloatField(default=0.0, verbose_name='推理耗时(ms)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='记录创建时间')),
            ],
            options={
                'verbose_name': '检测记录',
                'verbose_name_plural': '检测记录',
                'db_table': 'detection_records',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['device_id', 'timestamp'], name='detection_r_device__76479c_idx'), models.Index(fields=['is_anomaly', 'timestamp'], name='detection_r_is_anom_79b057_idx'), models.Index(fields=['attack_type', 'timestamp'], name='detection_r_attack__b5c1a2_idx')],
            },
        ),
    ]
