# Generated by Django 4.2.27 on 2025-12-12 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='设备ID')),
                ('name', models.CharField(max_length=128, verbose_name='设备名称')),
                ('device_type', models.CharField(choices=[('camera', '智能摄像头'), ('door_lock', '智能门锁'), ('sensor', '传感器'), ('gateway', '网关'), ('other', '其他')], default='other', max_length=20, verbose_name='设备类型')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP地址')),
                ('mac_address', models.CharField(blank=True, max_length=17, null=True, verbose_name='MAC地址')),
                ('status', models.CharField(choices=[('online', '在线'), ('offline', '离线'), ('warning', '告警')], default='offline', max_length=20, verbose_name='状态')),
                ('location', models.CharField(blank=True, max_length=128, null=True, verbose_name='位置')),
                ('is_trusted', models.BooleanField(default=True, verbose_name='是否可信')),
                ('last_seen', models.DateTimeField(blank=True, null=True, verbose_name='最后在线时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '设备',
                'verbose_name_plural': '设备',
                'db_table': 'devices',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='DeviceStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, verbose_name='统计日期')),
                ('total_requests', models.IntegerField(default=0, verbose_name='总请求数')),
                ('normal_count', models.IntegerField(default=0, verbose_name='正常请求数')),
                ('anomaly_count', models.IntegerField(default=0, verbose_name='异常请求数')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='devices.device')),
            ],
            options={
                'verbose_name': '设备统计',
                'verbose_name_plural': '设备统计',
                'db_table': 'device_stats',
                'ordering': ['-date'],
                'unique_together': {('device', 'date')},
            },
        ),
    ]
